In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

filename = '/content/drive/MyDrive/PTDataScience/PandasForDataManipulation/Proyecto/sales_predictions.csv'
sales_df = pd.read_csv(filename)

In [ ]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [ ]:
sales_df.shape

(8523, 12)

In [ ]:
sales_df.head()

  Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0           FDA15         9.30  ...  Supermarket Type1          3735.1380
1           DRC01         5.92  ...  Supermarket Type2           443.4228
2           FDN15        17.50  ...  Supermarket Type1          2097.2700
3           FDX07        19.20  ...      Grocery Store           732.3800
4           NCD19         8.93  ...  Supermarket Type1           994.7052

[5 rows x 12 columns]

In [ ]:
sales_df.tail()

     Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
8518           FDF22        6.865  ...  Supermarket Type1          2778.3834
8519           FDS36        8.380  ...  Supermarket Type1           549.2850
8520           NCJ29       10.600  ...  Supermarket Type1          1193.1136
8521           FDN46        7.210  ...  Supermarket Type2          1845.5976
8522           DRG01       14.800  ...  Supermarket Type1           765.6700

[5 rows x 12 columns]

In [ ]:
sales_df.loc[sales_df['Item_Weight'].isnull()]

     Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
7              FDP10          NaN  ...  Supermarket Type3          4022.7636
18             DRI11          NaN  ...  Supermarket Type3          2303.6680
21             FDW12          NaN  ...  Supermarket Type3          4064.0432
23             FDC37          NaN  ...      Grocery Store           214.3876
29             FDC14          NaN  ...      Grocery Store           125.8362
...              ...          ...  ...                ...                ...
8485           DRK37          NaN  ...  Supermarket Type3          6261.8490
8487           DRG13          NaN  ...  Supermarket Type3          4111.3150
8488           NCN14          NaN  ...  Supermarket Type3          2756.4120
8490           FDU44          NaN  ...      Grocery Store           487.3656
8504           NCN18          NaN  ...  Supermarket Type3          4138.6128

[1463 rows x 12 columns]

In [ ]:
item_weight = sales_df.pivot_table(values='Item_Weight', index='Item_Identifier')

is_null = sales_df['Item_Weight'].isnull()

temp = pd.DataFrame(sales_df) 
temp[is_null,'Item_Weight'] = sales_df.loc[is_null,'Item_Identifier'].apply(lambda x:  item_weight.at[x,'Item_Weight'])
temp

KeyError: ignored